version: '3.8'

services:
  db:
    image: mysql:9
    container_name: mysql_db
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  
  server:
    depends_on:
      - db
    image: onefin-server:0.0.1
    restart: always
    ports:
      - "8080:80"

  client:
    depends_on:
      - server
    image: onefin-client:0.0.1
    restart: always
    ports:
      - "8081:80"
  
  admin:
    depends_on:
      - server
    image: onefin-admin:0.0.1
    restart: always
    ports:
      - "8082:80"

volumes:
  db_data:
