name: Deploy to Remote Server

on:
  push:
    branches:
      - main
      - github-actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          echo "$ENV_VARS" > .env
          cat .env

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ec2-54-153-53-58.us-west-1.compute.amazonaws.com
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY  }}
          source: "./"
          target: "~"

      - name: Add ssh hosts
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan ec2-54-153-53-58.us-west-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Run Docker Compose
        run: |
          ssh ubuntu@ec2-54-153-53-58.us-west-1.compute.amazonaws.com "cd ~ && docker compose down && docker compose up --build -d "